apiVersion: v1
kind: Namespace
metadata:
  name: sales
  labels:
    domain: sales
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: tenant-services
  labels:
    domain: tenant-services
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: finance
  labels:
    domain: finance
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: data
  labels:
    domain: data
    environment: production
