apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: tenant-services
spec:
  hard:
    requests.cpu: "20"
    requests.memory: 40Gi
    limits.cpu: "40"
    limits.memory: 80Gi
    persistentvolumeclaims: "10"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: object-counts
  namespace: tenant-services
spec:
  hard:
    pods: "50"
    services: "20"
    secrets: "50"
    configmaps: "50"
